"""remove trades.id

Revision ID: 299f37871738
Revises: 86c3714a1ad3
Create Date: 2026-04-04 04:23:33.063975

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '299f37871738'
down_revision: Union[str, Sequence[str], None] = '86c3714a1ad3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('trades', 'tx_hash',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.drop_column('trades', 'id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('trades', sa.Column('id', sa.BIGINT(), autoincrement=True, nullable=False))
    op.alter_column('trades', 'tx_hash',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###
